# ------- Builder Stage -------
FROM maven:3.9-eclipse-temurin-17 AS builder
WORKDIR /app

# Copy pom.xml first (cache maven dependencies)
COPY pom.xml .
RUN mvn -q dependency:go-offline

# Then copy source
COPY src ./src

# Build jar
RUN mvn -q clean package -DskipTests

# ------- Runtime Stage -------
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# Copy only final fat-jar
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
