# 1. Builder stage (fat jar banane ke liye)
FROM eclipse-temurin:17-jdk AS builder
WORKDIR /app

# Copy maven files first to cache dependencies
COPY pom.xml .
RUN mvn -q dependency:go-offline

# Ab source code copy
COPY src ./src

# Jar build karo (fat-jar)
RUN mvn -q clean package -DskipTests

# 2. Runtime stage (final docker image)
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# fat-jar copy kro builder stage se
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
